### ISSUE TITLE
pep8speaks only returns W292 codes even when not relevant or ignored

### ISSUE THREAD

**Issue by Eskapp** [pep8speaks-org/pep8speaks#165]
**Context:**
I went back working on a private project for which we have a fork of pep8speaks as a webhook (done as suggested in https://github.com/OrkoHunter/pep8speaks/wiki/Instructions-to-deploy-a-fork)

Things were working perfectly by the end of 2018 as this screenshot proves:
![sc1](https://user-images.githubusercontent.com/18263140/79383781-c5fd6880-7f33-11ea-98b3-9021403f9e94.PNG)

Coming back working on this project, pep8speaks now only sees W292 issues which are non-existent (not reported when everything was working fine). I created a commit adding one empty line in the middle of a file and this is the output:
![sc2](https://user-images.githubusercontent.com/18263140/79384076-44f2a100-7f34-11ea-8050-d418fb03695f.PNG)

It basically lists all the files that have been modified and returns W292 for each one of them.

I have been playing around with the `.pep8speaks.yml` file for hours now. I have this behavior on all repositories to which I add the webhook.

**`.pep8speaks.yml` file** that I have:

```
# File : .pep8speaks.yml

scanner:
    diff_only: False  # If True, errors caused by only the patch are shown

pycodestyle:
    max-line-length: 120
    ignore:  # Errors and warnings to ignore
        - E741,  # do not use variables named 'l', 'O', or 'I'
        - E122,  # continuation line missing indentation or outdented
        - E127,  # continuation line over-indented for visual indent
        - E128,  # continuation line under-indented for visual indent
        - W503,  # line break occurred before a binary operator
        - E402,  # module level import not at top of file
```

Among the **things that I've tried** without success:
- Removing the commas
- Adding W292 to the `ignore` section
- Specifying the linter as `flake8` or `pycodestyle`
The result is the same every time, W292 is returned for all the modified files. I am clueless as the next step to take to get this working as it was before.
