### ISSUE TITLE
pep8speaks 1.7 does not comment in my PR

### ISSUE THREAD

**Issue by Eskapp** [pep8speaks-org/pep8speaks#168]
I deployed a fork of pep8speaks with the most recent release 1.7 following the instructions given in https://github.com/OrkoHunter/pep8speaks/wiki/Instructions-to-deploy-a-fork. I added the webhook to my repository and I can see that the deliveries go through with status 200.

However, whatever amount of "PEP8 mistakes" I add to my files, the bot does not comment in my PR.
It used to do as shown in #165 but now it does not.

My config file is the following:
```
# File : .pep8speaks.yml - Documentation: https://github.com/OrkoHunter/pep8speaks

scanner:
    diff_only: False  # If True, errors caused by only the patch are shown
    linter: pycodestyle 

pycodestyle:
    max-line-length: 120
    ignore:  # Errors and warnings to ignore
        - E741,  # do not use variables named 'l', 'O', or 'I'
        - W503,  # line break occurred before a binary operator
```

I tried with `flake8` and with `diff_only` to `True` as well and the result is the same.

Any hint on what could be wrong?
