### ISSUE TITLE
Feature Request: Allow PEP8Speaks to be run as a CI job for private/forks

### ISSUE THREAD

**Issue by OrkoHunter** [pep8speaks-org/pep8speaks#169]
PEP8Speaks needs to be hosted on a server to be run. A GitHub webhook sends payloads to the server via "GitHub app" and the server does all the magic. For users who want to run PEP8Speaks on a private repository, it is recommended to [deploy a fork](https://github.com/OrkoHunter/pep8speaks/wiki/Instructions-to-deploy-a-fork).

There can be an even easier distribution possible for PEP8Speaks. This is to run it on the repository's CI as a lint job. If the user has setup Travis/CircleCI/etc. on their repository (for building and testing their PRs), they should be able to add a job for PEP8Speaks.

```yml
# (CircleCI example)
- run:
  - name: Install and run PEP8Speaks # https://github.com/OrkoHunter/pep8speaks
  - command: |
    pip install https://github.com/OrkoHunter/pep8speaks
    pep8speaks --gh_token=${GITHUB_TOKEN} --pr_url=${CIRCLE_PULL_REQUEST} --<extra_config_key=value>
```

PEP8Speaks needs to be converted into a Python package which generates a CLI `pep8speaks`. The CLI takes few parameters like GitHub token and Pull Request information, and it does exactly what PEP8Speaks should do (Comment on the PR by following `.pep8speaks.yml`).
